### ISSUE TITLE
딜 상품 목록 조회 API

### ISSUE THREAD

**Issue by daadaadaah** [f-lab-edu/hee-commerce#30]
# What
## 화면
- [딜 상품 목록 페이지](https://ovenapp.io/view/UuIm813yqxt4va9VHKgIvlJlZ9k7Nrov/CrFzx)

## 요구사항
1+2. 사용자는 무한스크롤로 다음과 같은 정보를 가진 `딜 오픈 상품`과 `매진 상품` 목록을 볼 수 있다. 단, 매진 상품은 상세보기나 주문은 할 수 없다.
> 1. 오전 10시 ~ 오전 11시 : 당일 오픈 딜 상품 목록 보여주기
> 2. 오전 11시 ~ 오후 12시 : 당일 마감 딜 상품 목록 보여주기 -> 다음날 오픈 예정 딜 상품을 MySQL -> Redis로 flush 하는 시간 고려해서 여유시간 1시간 둠
> 3. 오후 12시 ~ 오전 0시 : 다음날 오픈 예정 딜 상품 목록 보여주기
> 4. 오전 0시 ~ 오전 10시 : 당일 오픈 예정 딜 상품 목록 보여주기

(1) 딜 상품 대표 이미지 썸네일
(2) 딜 상품 타이틀
(3) 딜 상품 재고수량
(4) 원가격
(5) 할인 금액 또는 할인율
(6) 할인가격
(7) 딜 상품 상태(오픈 전, 오픈, 품절, 마감)

3. 사용자는 총 딜 상품의 수를 볼 수 있다. 
-  총 상품의 갯수가 1만건이고, 그 중에서 딜 상품은 하루에 최대 50개까지만 등록할 수 있다.
4. 사용자는 다음과 같은 순서로 정렬할 수 있다.
    - 기본 정렬 순 : 일단은 등록 순으로 하고, 검색 기능 구현하면서 기본 정렬로 어떻게 할지 고민해보기
    - 높은가격 순
    - 낮은가격 순
  
# How
- [x] [API 문서](https://darling-sorbet-0583ef.netlify.app/#_%EB%94%9C_%EC%9C%A0%ED%98%95%EB%B3%84_%EB%94%9C_%EC%83%81%ED%92%88_%EB%AA%A9%EB%A1%9D_%EC%A1%B0%ED%9A%8C)
- [x] Controller 구현 및 테스트 코드 작성
- [x] Service 구현 및 테스트 코드 작성
- [ ] Repository 구현
- [x] [상속과 동적 바인딩](https://github.com/f-lab-edu/hee-commerce/pull/47#discussion_r1233357775)을 이용하여 DealController 수정하려고 했으나, 좀더 포괄적인 네이밍을 사용하는 방법으로 문제를 해결(https://github.com/f-lab-edu/hee-commerce/pull/72)

# TODO
- [] #32 완성되면, API 문서 수정하기
