### ISSUE TITLE
딜 상품 상세보기 API

### ISSUE THREAD

**Issue by daadaadaah** [f-lab-edu/hee-commerce#31]
# What
## 화면
- [딜 상품 상세보기 페이지](https://ovenapp.io/view/UuIm813yqxt4va9VHKgIvlJlZ9k7Nrov/ra8AS)

## 요구사항
0. p9이 500ms -> 전체 요청 중에 상위 90%의 요청의 response 타임이 500ml이다.
1. 사용자는 행사 종료시까지 남은 시간을 볼 수 있다.
2. 사용자는 딜 상품의 재고수량을 볼 수 있다.
3. 사용자는 딜 상품 대표 이미지를 볼 수 있다. -> 이미지 사이즈
4. 사용자는 딜 상품 설명 이미지를 볼 수 있다. -> 이미지 사이즈
5. 사용자는 딜 상품 타이틀을 볼 수 있다.
6. 사용자는 딜 상품 원가격을 볼 수 있다.
7. 사용자는 딜 상품 할인 가격을 볼 수 있다.
8. 사용자는 딜 상품 수량을 선택할 수 있다. 인당 최대 주문 개수는 제한이 있다.
9. 사용자는 딜 상품을 바로 구매할 수 있다.

# How
- [ ] API 문서
- [ ] Controller 구현 및 테스트 코드 작성
- [ ] Service 구현 및 테스트 코드 작성
- [ ] Repository 구현

# TODO
- [] #32 완성되면, API 문서 수정하기
